# -*- coding: utf-8 -*-
"""ARIMA_models.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rYKwZiEWHfjayzIssfzlw5XBQirAMjhl

# INIT
"""

install.packages(c("forecast", "aTSA", "datasets", "Metrics", "ISLR"))

devtools::install_github ("bdemeshev/sophisthse")

library("forecast")
library('ISLR')
library("aTSA")
library("datasets")
library("Metrics")
library("sophisthse")
library(tseries)

"""Необходимо для вызова shell command, например чтобы скачать датасет"""

sh <- function(command, ...) {
  result <- system(command, intern = TRUE, ...)
  cat(paste0(result, collapse = "\n"))
}

sh("ls & echo 'hello world'")

"""Построение различных ARIMA(p, d, q) моделей"""

# Создаст все возможные наборы ARIMA с различными значениями авторегрессий и скользящего среднего
# Вернет датафрейм с оценками MAE и RMSE
createArimas <- function(learn, test, max_p, max_q, d){
  qq <- c()
  pp <- c()
  dd <- c()
  RMSE <- c()
  MAE <- c()
  for (p in 0:max_p)
  {
    for (q in 0:max_q)
    {
      res <- tryCatch(
        {
          model = Arima(learn, order = c(p,d,q))
          pred = predict(model, n.ahead = 12)
          RMSE = append(RMSE, rmse(test, pred$pred))
          MAE = append(MAE, mae(test, pred$pred))
          pp = append(pp, p)
          qq = append(qq, q)
        },
        error = function(cond)
        {return(NA)})
    }
  }
  DF_RMSE_MAE = data.frame(p = pp, q = qq, RMSE, MAE)
  return(DF_RMSE_MAE)
}

"""# Индекс реальных денежных доходов населения

## Временной ряд
"""

im <- sophisthse("HHI_M_DIRI")[, "HHI_M_DIRI"]

im

tsdisplay(im, main = 'Временной ряд', ci.col = "black")

adf.test(im)

"""p > 0.05

Автокорелляция снижается слишком медленно, нет нулевых коэффициентов. Ряд не станционарный, также наблюдается некоторая сезонность в частных автокорреляциях.
"""

im_2diff <- diff(im)

tsdisplay(im_2diff, main = 'Временной ряд', ci.col = "black")

adf.test(im_2diff)

"""p < 0.05

При разницах между лагами действительно отчетливо наблюдается сезонность. 
ACF становится не значимым после 5 лага, в то время как PACF постепенно снижается. Можно предположить модель ARIMA(0, 1, 5).
Попробуем считать временной ряд с 2000 года.
"""

im2k <- window(im, start = 2000)

adf.test(im2k)

tsdisplay(diff(im2k), main = 'Временной ряд', ci.col = "black")

"""ACF также постепенно затухает, в то время как PACF резко обрывается. Можно предположить модель ARIMA(2, 2, 0)"""

im2k_test = tail(im2k, 12)
im2k_learn = head(im2k, -12)

im2k_learn

im2k_test

arma200 <- predict(Arima(im2k_learn, order=c(0, 1, 5)), n.ahead = 12)
arma200

"""## Поиск лучшей модели ARIMA.auto"""

auto2k = auto.arima(im2k_learn, trace= TRUE, ic ="aicc", approximation = FALSE, stepwise = FALSE, seasonal=TRUE)
summary(auto2k)

"""Коэффициенты ARIMA(3, 2, 0)(0, 0, 2)[12] (авторегрессия 3, сезонность 12) значимые, $\sigma^2$ мал"""

im2k_prediction = predict(auto2k, n.ahead = length(im2k_test))
im2k_prediction

im2k_test

"""## Перебор qmax pmax

* AR = 6, так как PACF обрывается на втором лаге
* MA = 5, так как ACF резко обрывается на пятом лаге
"""

im_arimas <- createArimas(im2k_learn, im2k_test, 6, 5, 1)
bestModels <- rbind(
  im_arimas[which.min(im_arimas$RMSE),],
  im_arimas[which.min(im_arimas$MAE),]
)
bestModels

"""ARIMA(3, 1, 2)

ARIMA(5, 1, 4)
"""

arima312 <- predict(Arima(im2k_learn, order=c(3, 1, 2)), n.ahead = length(im2k_test))
arima514 <- predict(Arima(im2k_learn, order=c(5, 1, 4)), n.ahead = length(im2k_test))

"""## Сравнение моделей"""

plot(im2k_prediction$pred,
     type = "l",
     col = 2,
     ylim = c(130, 330),
     xlab = "Year",
     ylab = "Values")
lines(arma200$pred,
      type = "l",
      col = 3)
lines(arima312$pred,
      type = "l",
      col = 4)
lines(arima514$pred,
      type = "l",
      col = 5)
lines(im2k_test,
      type = "l",
      col = 6)
legend("topright", legend = c("Auto ARIMA(0, 1, 1)", "ARIMA(0, 1, 5)", "ARIMA(3, 1, 2)", "ARIMA(5, 1, 4)","Real"), col=c(2, 3, 4, 5, 6), pch=1)

"""График для ARIMA(3, 2, 0) выглядит точнее, но проверим также RMSE и MAE"""

RMSEa <- rmse(im2k_test, im2k_prediction$pred)
MAEa <- mae(im2k_test, im2k_prediction$pred)

RMSEh <- rmse(im2k_test, arma200$pred)
MAEh <- mae(im2k_test, arma200$pred)

print(c(c(RMSEa, MAEa), c(RMSEh, MAEh)))
print(c(26.07776, 17.61363))
print(c(26.83586,	16.91886))

"""*Итог: для прогноза стоит использовать ARIMA(2, 2, 5)*

# Индекс реального ВВП, с поправкой на сезонность

## Временной ряд
"""

hhi <- ts(sophisthse("GDPEA_Q_DIRI")[, "GDPEA_Q_DIRI_SA"], frequency=4)

hhi

tsdisplay(hhi, main = 'Временной ряд', ci.col = "black")

adf.test(hhi)

"""ACF снижается слишком медленно, явно виден тренд. p > 0.05. Ряд не станционарный"""

hhi_diff <- diff(hhi)

tsdisplay(hhi_diff, main = 'Временной ряд', ci.col = "black")

adf.test(hhi_diff)

"""ACF быстро снижается, уже на третьем лаге нулевая автокорреляция. p < 0.05. Наблюдается сезонность. Ряд станционарен.

PACF затухает плавнее, чем ACF, который обрывается на первом лаге. Можно предположить ARIMA(0, 1, 1)
"""

hhi_test = tail(hhi, 12)
hhi_learn = head(hhi, -12)

arma001 <- predict(Arima(hhi_learn, order=c(0, 1, 1)), n.ahead = length(hhi_test))
arma001

"""## Поиск лучшей модели ARIMA.auto"""

autohhi = auto.arima(hhi_learn, trace= TRUE, ic ="aicc", approximation = FALSE, stepwise = FALSE, seasonal=TRUE)
summary(autohhi)

"""Выбрана модель $ARIMA(2, 2, 0)$ , коэффициенты значимые, $\sigma^2$ мал"""

hhi_prediction = predict(autohhi, n.ahead = length(hhi_test))
hhi_prediction

"""## Перебор qmax pmax

* AR = 2, так как PACF резко обрывается на втором лаге
* MA = 1, так как ACF резко обрывается на первом лаге
"""

hhi_arimas <- createArimas(hhi_learn, hhi_test, 2, 1, 1)
bestModels <- rbind(
  hhi_arimas[which.min(hhi_arimas$RMSE),],
  hhi_arimas[which.min(hhi_arimas$MAE),]
)
bestModels

"""**ARIMA**(0, 1, 0)"""

arima010 <- predict(Arima(hhi_learn, order=c(0, 1, 0)), n.ahead = length(hhi_test))

"""## Сравнение моделей"""

plot(hhi_prediction$pred,
     type = "l",
     col = 2,
     ylim = c(150, 190),
     xlab = "Year",
     ylab = "Values")
lines(arma001$pred,
     type = "l",
     col = 3)
lines(arima010$pred,
      type = "l",
      col = 4)
lines(hhi_test,
      type = "l",
      col = 5)
legend("topright", legend = c("AUTO ARIMA(2, 2, 0)", "ARIMA(0,1,1)", "ARIMA(0, 1, 0)", "Real"), col=c(2, 3, 4, 5), pch=1)

RMSEa <- rmse(hhi_test, hhi_prediction$pred)
MAEa <- mae(hhi_test, hhi_prediction$pred)

RMSEh <- rmse(hhi_test, arma001$pred)
MAEh <- mae(hhi_test, arma001$pred)
print(c(RMSEa, MAEa))
print(c(RMSEh, MAEh))
print(c(3.119829,	2.6))

"""Наилучшая оценка у ARIMA(0, 1, 0)

# [Monthly gold prices since 1950 in USD (London market)](https://github.com/datasets/gold-prices)
"""

sh("wget https://raw.githubusercontent.com/datasets/gold-prices/main/data/monthly.csv -O gold_m.csv")
gold <- read.csv('gold_m.csv')$Price

"""## Временной ряд"""

gold <- ts(gold, frequency=12)
tsdisplay(gold, main = 'Временной ряд', ci.col = "black")

"""Цена до 25 года особо не меняется"""

gold2 <- window(gold, start = 25)
tsdisplay(gold2, main = 'Временной ряд', ci.col = "black")

"""Автокорелляция снижается слишком медленно, нет нулевых коэффициентов. Ряд не станционарный, наблюдается некоторая сезонность в частных автокорреляциях."""

gold_diff <- diff(gold2)
tsdisplay(gold_diff, main = 'Временной ряд', ci.col = "black")

"""Автокорреляция быстро снижается, видна зависимость между ACF и PACF. Наблюдается сезонность. ACF резко становится не значимым с первого же лага но затем постепенно затухает, PACF не значим после второого лага. Можно предположить ARIMA(0, 1, 2)"""

gold_test = tail(gold2, 12)
gold_learn = head(gold2, -12)

arma02 <- predict(Arima(gold_learn, order=c(0, 1, 2)), n.ahead = length(gold_test))
arma02

"""## Поиск лучшей модели ARIMA.auto"""

autogold = auto.arima(gold_learn, trace= TRUE, ic ="aicc", approximation = FALSE, stepwise = FALSE, seasonal=TRUE)
summary(autogold)

gold_prediction = predict(autogold, n.ahead = length(gold_test))
gold_prediction

"""## Перебор qmax pmax

* AR = 2, так как PACF резко обрывается на втором лаге
* MA = 1, так как ACF резко обрывается на первом лаге
"""

gold_arimas <- createArimas(gold_learn, gold_test, 2, 1, 1)
bestModels <- rbind(
  gold_arimas[which.min(gold_arimas$RMSE),],
  gold_arimas[which.min(gold_arimas$MAE),]
)
bestModels

"""ARIMA(1, 1, 1)"""

arima111 <- predict(Arima(gold_learn, order=c(1, 1, 1)), n.ahead = length(gold_test))

"""## Сравнение моделей"""

plot(gold_prediction$pred,
     type = "l",
     col = 2,
     ylim = c(1200, 1350),
     xlab = "Month",
     ylab = "Values")
lines(arma02$pred,
      type = "l",
      col = 3)
lines(arima111$pred,
      type = "l",
      col = 4)
lines(gold_test,
      type = "l",
      col = 5)
legend("topright", legend = c("Auto ARIMA(0, 1, 5)", "ARIMA(0, 1, 2)", "ARIMA(1, 1, 1)", "Real"), col=c(2, 3, 4, 5), pch=1)

RMSEa <- rmse(gold_test, gold_prediction$pred)
MAEa <- mae(gold_test, gold_prediction$pred)

RMSEh <- rmse(gold_test, arma02$pred)
MAEh <- mae(gold_test, arma02$pred)
print(c(RMSEa, MAEa))
print(c(RMSEh, MAEh))
print(c(55.61557, 43.41873))

"""Наилучшее предсказание у модели ARIMA(1, 1, 1)

#[Europe Brent and WTI (Western Texas Intermediate) Spot Prices](https://github.com/datasets/oil-prices)
"""

sh("wget https://raw.githubusercontent.com/datasets/oil-prices/main/data/brent-monthly.csv -O brent_m.csv")

"""## Временной ряд"""

brent <- ts(read.csv('brent_m.csv')$Price, frequency=12)

tsdisplay(brent, main = 'Временной ряд', ci.col = "black")

"""До 15 года цена меняется не сильно"""

brent2 <- window(brent, start = 15)

tsdisplay(brent2, main = 'Временной ряд', ci.col = "black")

"""Наблюдается сезонность, ACF снижается слишком медленно, ряд не станционарный"""

brent_diff <- diff(log(brent2))
tsdisplay(brent_diff, main = 'Временной ряд', ci.col = "black")

"""Наблюдается явная сезонность, ACF затухает более плавно и сразу не значим, PACF обрывается после первого лага. ARIMA(0, 1, 1)?"""

brent_test = tail(log(brent2), 12)
brent_learn = head(log(brent2), -12)

arma01 <- predict(Arima(brent_learn, order=c(0, 1, 1)), n.ahead = length(brent_test))
arma01

"""## Поиск лучшей модели ARIMA.auto"""

autobrent = auto.arima(brent_learn, trace= TRUE, ic ="aicc", approximation = FALSE, stepwise = FALSE, seasonal=TRUE)
summary(autobrent)

brent_prediction = predict(autobrent, n.ahead = length(brent_test))
brent_prediction

"""## Перебор qmax pmax

* AR = 2, так как PACF резко обрывается на втором лаге
* MA = 3, как наиболее ближайший значимый лаг
"""

brent_arimas <- createArimas(brent_learn, brent_test, 2, 3, 1)
bestModels <- rbind(
  brent_arimas[which.min(brent_arimas$RMSE),],
  brent_arimas[which.min(brent_arimas$MAE),]
)
bestModels

arima000 <- predict(Arima(brent_learn, order=c(1, 1, 2)), n.ahead = length(brent_test))

"""## Сравнение моделей"""

plot(brent_test,
     type = "l",
     col = 2,
     xlab = "Month",
     ylab = "Values")
lines(brent_prediction$pred,
      type = "l",
      col = 3)
lines(arma01$pred,
      type = "l",
      col = 4)
lines(arima000$pred,
      type = "l",
      col = 5)
legend("topright", legend = c("Real", "Auto ARIMA(0, 1, 4)", "ARIMA(0, 1, 1)", "ARIMA(1, 1, 2)"), col=c(2, 3, 4, 5), pch=1)

RMSEa <- rmse(brent_test, brent_prediction$pred)
MAEa <- mae(brent_test, brent_prediction$pred)

RMSEh <- rmse(brent_test, arma01$pred)
MAEh <- mae(brent_test, arma01$pred)
print(c(c(RMSEa, MAEa), '\n', c(RMSEh, MAEh)))
print(c(0.1176999,	0.09508145))

"""#[Time series of major Natural Gas Prices](https://github.com/datasets/natural-gas)"""

sh("wget https://raw.githubusercontent.com/datasets/natural-gas/master/data/monthly.csv -O gas_m.csv")

"""## Временной ряд"""

gas <- ts(read.csv('gas_m.csv')$Price)
tsdisplay(gas, main = 'Временной ряд', ci.col = "black")

gas_diff2 <- diff(gas)
tsdisplay(gas_diff2, main = 'Временной ряд', ci.col = "black")

"""ACF и PACF практически идентичны и не значимые. ARIMA(5, 1, 0) или ARIMA(0, 1, 5)?"""

gas_test = tail(gas, 12)
gas_learn = head(gas, -12)

arma50 <- predict(Arima(gas_learn, order=c(5, 1, 0)), n.ahead = length(gas_test))
arma50

arma05 <- predict(Arima(gas_learn, order=c(0, 1, 5)), n.ahead = length(gas_test))
arma05

"""## Поиск лучшей модели ARIMA.auto"""

autogas = auto.arima(gas_learn, trace= TRUE, ic ="aicc", approximation = FALSE, stepwise = FALSE, seasonal=TRUE)
summary(autogas)

gas_prediction = predict(autogas, n.ahead = length(gas_test))
gas_prediction

"""## Перебор qmax pmax

* AR = 5, ближайший значимый лаг
* MA = 5, ближайший значимый лаг
"""

gas_arimas <- createArimas(gas_learn, gas_test, 5, 5, 1)
bestModels <- rbind(
  gas_arimas[which.min(gas_arimas$RMSE),],
  gas_arimas[which.min(gas_arimas$MAE),]
)
bestModels

arima512 <- predict(Arima(gas_learn, order=c(5, 1, 2)), n.ahead = length(gas_test))
arima213 <- predict(Arima(gas_learn, order=c(2, 1, 3)), n.ahead = length(gas_test))

"""## Сравнение моделей"""

plot(gas_test,
     type = "l",
     col = 2,
     xlab = "Month",
     ylab = "Values")
lines(gas_prediction$pred,
      type = "l",
      col = 3)
lines(arma05$pred,
      type = "l",
      col = 4)
lines(arma50$pred,
      type = "l",
      col = 5)
lines(arima512$pred,
      type = "l",
      col = 6)
lines(arima213$pred,
      type = "l",
      col = 7)
legend("topright", legend = c("Real", "Auto ARIMA(1, 1, 1)", "ARIMA(0, 1, 5)", "ARIMA(5, 1, 0)", "ARIMA(5, 1, 2)", "ARIMA(2, 1, 3)"), col=c(2, 3, 4, 5, 6, 7), pch=1)

RMSEa <- rmse(gas_test, gas_prediction$pred)
MAEa <- mae(gas_test, gas_prediction$pred)

RMSEh <- rmse(gas_test, arma05$pred)
MAEh <- mae(gas_test, arma05$pred)
RMSEh2 <- rmse(gas_test, arma50$pred)
MAEh2 <- mae(gas_test, arma50$pred)
print(c(c(RMSEa, MAEa), '\n', c(RMSEh, MAEh), '\n', c(RMSEh2, MAEh2)))
print(c(0.2980879,	0.1907153))
print(c(0.3052595,	0.1785848))

"""Наилучшая оценка RMSE у ARIMA(5, 1, 0), MAE у ARIMA(0, 1, 5)

# [Nasa GISS Surface Temperature (GISTEMP) ](https://github.com/datasets/global-temp-anomalies)
"""

sh("wget https://raw.githubusercontent.com/datasets/global-temp-anomalies/master/data/global-temp-annual.csv -O gistemp.csv")

"""Очень интересный датасет, подойдет для многомерного исследования, хоть и так понятно что аномальная температура наверняка имеет зависимости с аномальной температурой в воде. В настоящее время будет проведено исследование на аномальные температуры на поверхности.

## Временной ряд
"""

gistemp <- ts(read.csv('gistemp.csv')$Land)
tsdisplay(gistemp, main = 'Временной ряд', ci.col = "black")

"""Явно виден тренд и сезонность, ряд не станционарен. Начнем подсчет с 1960 года"""

gistemp <- window(gistemp, start = 80)

gistemp_diff <- diff(gistemp)
tsdisplay(gistemp_diff, main = 'Временной ряд', ci.col = "black")

"""Явно наблюдается сезонность, ACF обрывается на первом же лаге, PACF снижается постепенно, ARIMA(0, 1, 1)?"""

gistemp_test = tail(gistemp, 12)
gistemp_learn = head(gistemp, -12)

arma01 <- predict(Arima(gistemp_learn, order=c(0, 1, 1)), n.ahead = length(gistemp_test))
arma01

"""## Поиск лучшей модели ARIMA.auto"""

autogistemp = auto.arima(gistemp_learn, trace= TRUE, ic ="aicc", approximation = FALSE, stepwise = FALSE, seasonal=TRUE)
summary(autogistemp)

"""Auto ARIMA также выбрал модель ARIMA(0, 1, 1).

## Перебор qmax pmax

* AR = 2, ближайший значимый лаг
* MA = 1, ближайший значимый лаг
"""

gistemp_arimas <- createArimas(gistemp_learn, gistemp_test, 2, 1, 1)
bestModels <- rbind(
  gistemp_arimas[which.min(gistemp_arimas$RMSE),],
  gistemp_arimas[which.min(gistemp_arimas$MAE),]
)
bestModels

arima110 <- predict(Arima(gistemp_learn, order=c(1, 1, 0)), n.ahead = length(gistemp_test))

"""## Сравнение моделей"""

plot(gistemp_test,
     type = "l",
     col = 2,
     xlab = "Years",
     ylab = "Values")
lines(arma01$pred,
      type = "l",
      col = 3)
lines(arima110$pred,
      type = "l",
      col = 4)
legend("topright", legend = c("Real", "ARIMA(0, 1, 1)", "ARIMA(1, 1, 0)"), col=c(2, 3, 4), pch=1)

RMSEa <- rmse(gistemp_test, arma01$pred)
MAEa <- mae(gistemp_test, arma01$pred)
print(c(RMSEa, MAEa))
print(c(	0.100097,	0.07838142))

"""ARIMA(1, 1, 0)"""